### ISSUE TITLE
Il testo

### ISSUE THREAD

**Issue by FabioZTessitore** [luca998/gesione_testo#2]
gestione del testo

**Comment by luca998** [comment]
Ok

**Comment by FabioZTessitore** [comment]
Molti tag si utilizzano per dare significato al testo.

Cosi' come p indica un paragrafo, h1 .. h6 le intestazioni abbiamo anche:

``` html
<abbr>      abbreviazioni
<acronym>   acronimi
<cite>      citazioni
<code>      codice sorgente
<dfn>       termini da definire
<em>        evidenza
<strong>    evidenza forte
<kbd>       da inserire con la tastiera
<samp>      testo di esempio
<var>       variabili
<pre>       testo preformattato
<address>   dati di contatto
```

**Comment by FabioZTessitore** [comment]
Alcuni caratteri hanno un significato speciale
e non possono essere inseriti direttamente nelle pagine Web.

I simboli `<` e `>` per esempio servono a delimitare i tag.

In questi casi si utilizzano dei codici:

``` html
&lt;    (less than)     minore
&gt;    (greater than)  maggiore
&amp;   (ampersand)     &
```

Anche per le lettere accentate vale un discorso analogo:

```
&eacute;  é
&egrave;  è
&ograve;  ò
...
```

**Comment by luca998** [comment]
Ok
