### ISSUE TITLE
esercitazione: il linguaggio C

### ISSUE THREAD

**Issue by FabioZTessitore** [luca998/gesione_testo#3]
![linguaggioc_pt1](https://cloud.githubusercontent.com/assets/3002194/13116855/ddb3ccc4-d59d-11e5-816a-c0914a0a8c53.png)
![linguaggioc_pt2](https://cloud.githubusercontent.com/assets/3002194/13116865/e5dfe7d4-d59d-11e5-929c-758d214ec1cf.png)

cerca di ottenere questo risultato

**Comment by FabioZTessitore** [comment]
ci sono problemi?

**Comment by FabioZTessitore** [comment]
qualcosa non va?

**Comment by luca998** [comment]
Prof ho avuto dei problemi con Ubuntu
Il 04/Apr/2016 15:42 "Fabio Z Tessitore" notifications@github.com ha
scritto:

**Comment by FabioZTessitore** [comment]
e ora li hai risolti?

**Comment by luca998** [comment]
Sisi
Il 05/Apr/2016 16:35 "Fabio Z Tessitore" notifications@github.com ha
scritto:

**Comment by FabioZTessitore** [comment]
ok, allora buon lavoro

**Comment by FabioZTessitore** [comment]
tutto bene, bravo.
gli elementi h2 possono andare dentro i div, insieme ai paragrafi
